apiVersion: apps/v1
kind: Deployment
metadata:
   name: desire-app
spec:
   strategy:
    type: Recreate
   selector:
    matchLabels:
      app: desire-app
   template:
    metadata:
      labels:
        app: desire-app
    spec:
      containers:
      - name: desire-app
        image: olehyfront/firstapp:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80